services:
  postgres:
    image: 'postgres:latest'
    environment:
      # Updated to match your application.yaml exactly!
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=Veyron07__'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  backend:
    build: .
    ports:
      - '8080:8080'
    environment:
      # This overrides the 'localhost' default in your app.yaml
      # It tells Spring Boot to talk to the 'postgres' container instead!
      - DB_URL=jdbc:postgresql://postgres:5432/ecommerce
    depends_on:
      - postgres
      - redis